#' @title  Step by Step run Analysis
#'
#' @author Maher Daoud
#' 
################## Step1: Analysis project initiation #############
result <- kobo_projectinit() ## Create analysis project structure
if(class(result) == "try-error"){
  print(result)
  return(FALSE)
}
form <- "form.xls" ## The name of xlsform file
mainDir <- kobo_getMainDirectory() ## return current working directory

################# Step2: Check if the file is exist #############
form <- "form.xls" ## The name of the xlsform that exist under data folder
if (!file.exists(paste0(mainDir, "/data/",form))) {
  print("Please make sure that this file exists with the same name under the data folder")
  return(FALSE)
}

################## Step3: Rename xlsform and Dataframes ##################
## Please make sure in the settings sheet that you mentioned the main data frame and all sub dataframes
## The name field must be filled with the same name of begin-repeat name.
## The name of the Main Data Frame must be always "MainDataFrame", just to indicate that is the main one
## ex: 
#     name	          | label	 |       value	      |             path
# 1  MainDataFrame    |   NA   | mainDataFrame.csv  | current-working-directory/data/mainDataFrame.csv
# 2  br1              |   NA   | begin-repeat1.csv  | current-working-directory/data/begin-repeat1.csv

result <- kobo_rename_xlsform_dataframes(form)
if(class(result) == "try-error"){
  print(result)
  return(FALSE)
}

################## Step4: Prepare xlsform #############
result <- kobo_prepare_form(form)
if(class(result) == "try-error"){
  print(result)
  return(FALSE)
}

################## Step5: Check Analysis Plan #############
result <- kobo_check_analysis_plan(form)
if(class(result) == "try-error"){
  print(result)
  return(FALSE)
}

################## Step6: Load Data #############
result <- kobo_load_data(form)
if(class(result) == "try-error"){
  print(result)
  return(FALSE)
}



############################## Generate Reports ###############################

################## Generate Crunching Report #############
result <- kobo_crunching_report(form)
if(class(result) == "try-error"){
  print(result)
  return(FALSE)
}

################## Generate Cluster Report #############
household <- read.csv(paste(mainDir, "data", "/household.csv", sep = "/", collapse = "/"), stringsAsFactors = F) ## This dataset will be generated by kobo_load_data
result <- kobo_cluster_report(frame = household, form)
if(class(result) == "try-error"){
  print(result)
  return(FALSE)
}

################## Generate Anonymisation Report #############
result <- kobo_anonymisation_report(frame = household, form)
if(class(result) == "try-error"){
  print(result)
  return(FALSE)
}

