########################
### Console Script #####
########################

library(koboloadeR)

#### Phase 1: Project Configurationn #############
## Configure name of the xlsform that exist under data folder
# - Change if required but better to keep the defautl one
form <- "form.xls"

## Extend xlsform with necessary column
kobo_prepare_form(form)

### Eventually Generate dummy data (uncomment below if required)
# kobo_dummy(form)

######################################################################################
### At this stage you can start working on your xlsform and fill it accordingly!!! ###
######################################################################################


#### Phase 2: Analysis Plan ###############################
kobo_check_analysis_plan(form)


#### Phase 3:  Load & process Data ###############################
kobo_load_data(form)



#### Phase 4: Generate Analysis Reports ###############################

##  Generate Crunching Report --> Describe
kobo_crunching_report(form)

## Generate Cluster Report  --> Discover
MainDataFrame <- read.csv(paste(mainDir, "data", "/MainDataFrame.csv", sep = "/", collapse = "/"), stringsAsFactors = F) ## This dataset will be generated by kobo_load_data
kobo_cluster_report(frame = MainDataFrame, form)

## Generate Prediction Report  --> Predict

## Generate Scoring Report  --> Prescribe


#### Phase 5: Statistical Disclosure control & Indicator sharing ###############################
## Generate Anonymisation Report
MainDataFrame <- read.csv(paste(mainDir, "data", "/MainDataFrame.csv", sep = "/", collapse = "/"), stringsAsFactors = F) ## This dataset will be generated by kobo_load_data
kobo_anonymisation_report(frame = MainDataFrame, form)

